# Generated by Django 5.2 on 2025-06-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
