services:
  - type: web
    name: ecommerce-app
    env: python
    region: oregon # or your preferred region
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ecommerce.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
